### ISSUE TITLE
stats & users

### ISSUE THREAD

**Issue by dotscript** [lukesUbuntu/cloudflare-api#1]
Hi can you add support for stats, Currently using this on a small project would also be good to see creating users etc.

**Comment by dotscript** [comment]
oh its you again... yes will be adding in stats, this class im building towards using for a blesta module, so it  is aimed for basic hosting needs.

**Comment by lukesUbuntu** [comment]
oh it's you again... yes will be adding in stats, this class im building for a blesta module, so it is aimed for basic hosting needs.

**Comment by lukesUbuntu** [comment]
@2adb4ad added analytics method , you can get the basic's from  https://api.cloudflare.com/#zone-analytics-dashboard on how to use. will make it easier later.

**Comment by lukesUbuntu** [comment]
added basic user update and user info @889c9dd
